#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Installer Utility Module

This module contains utilities for creating a Windows installer for the PhishGuard application.
"""

import os
import sys
import logging
import subprocess

logger = logging.getLogger('PhishGuard.Installer')


def create_installer():
    """Create a Windows installer for the PhishGuard application
    
    This function uses PyInstaller to create a standalone executable and
    then packages it into a Windows installer using NSIS.
    
    Returns:
        bool: True if the installer was created successfully, False otherwise
    """
    try:
        # Get the project root directory
        project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        
        # Create the PyInstaller command
        pyinstaller_cmd = [
            'pyinstaller',
            '--name=PhishGuard',
            '--windowed',
            '--icon=resources/icon.ico',
            '--add-data=resources;resources',
            '--hidden-import=win32gui',
            '--hidden-import=win32process',
            '--hidden-import=win32con',
            '--hidden-import=win32api',
            '--hidden-import=win32com',
            '--hidden-import=win32com.client',
            '--hidden-import=win32com.server',
            '--hidden-import=pythoncom',
            '--hidden-import=psutil',
            '--hidden-import=requests',
            '--hidden-import=bs4',
            '--hidden-import=lxml',
            '--hidden-import=sklearn',
            '--hidden-import=numpy',
            '--hidden-import=pandas',
            '--onefile',
            os.path.join(project_root, 'main.py')
        ]
        
        # Run PyInstaller
        logger.info("Running PyInstaller...")
        subprocess.run(pyinstaller_cmd, cwd=project_root, check=True)
        
        # Create the NSIS script
        nsis_script = os.path.join(project_root, 'installer.nsi')
        with open(nsis_script, 'w') as f:
            f.write("""
            ; PhishGuard Installer Script
            ; Generated by PhishGuard Installer Utility
            
            !include "MUI2.nsh"
            
            ; General
            Name "PhishGuard"
            OutFile "PhishGuard-Setup.exe"
            InstallDir "$PROGRAMFILES\\PhishGuard"
            InstallDirRegKey HKCU "Software\\PhishGuard" ""
            RequestExecutionLevel admin
            
            ; Interface Settings
            !define MUI_ABORTWARNING
            !define MUI_ICON "${NSISDIR}\\Contrib\\Graphics\\Icons\\modern-install.ico"
            !define MUI_UNICON "${NSISDIR}\\Contrib\\Graphics\\Icons\\modern-uninstall.ico"
            
            ; Pages
            !insertmacro MUI_PAGE_WELCOME
            !insertmacro MUI_PAGE_LICENSE "LICENSE.txt"
            !insertmacro MUI_PAGE_DIRECTORY
            !insertmacro MUI_PAGE_INSTFILES
            !insertmacro MUI_PAGE_FINISH
            
            !insertmacro MUI_UNPAGE_CONFIRM
            !insertmacro MUI_UNPAGE_INSTFILES
            
            ; Languages
            !insertmacro MUI_LANGUAGE "English"
            
            ; Installer Sections
            Section "PhishGuard" SecPhishGuard
                SetOutPath "$INSTDIR"
                
                ; Add files
                File "dist\\PhishGuard.exe"
                File "LICENSE.txt"
                File "README.md"
                
                ; Create uninstaller
                WriteUninstaller "$INSTDIR\\Uninstall.exe"
                
                ; Create shortcuts
                CreateDirectory "$SMPROGRAMS\\PhishGuard"
                CreateShortcut "$SMPROGRAMS\\PhishGuard\\PhishGuard.lnk" "$INSTDIR\\PhishGuard.exe"
                CreateShortcut "$SMPROGRAMS\\PhishGuard\\Uninstall.lnk" "$INSTDIR\\Uninstall.exe"
                CreateShortcut "$DESKTOP\\PhishGuard.lnk" "$INSTDIR\\PhishGuard.exe"
                
                ; Add to Add/Remove Programs
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "DisplayName" "PhishGuard"
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "UninstallString" "$\"$INSTDIR\\Uninstall.exe$\""
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "QuietUninstallString" "$\"$INSTDIR\\Uninstall.exe$\" /S"
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "InstallLocation" "$\"$INSTDIR$\""
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "DisplayIcon" "$\"$INSTDIR\\PhishGuard.exe$\""
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "Publisher" "PhishGuard"
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "DisplayVersion" "1.0.0"
                WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "NoModify" 1
                WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "NoRepair" 1
                
                ; Add to startup
                WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Run" "PhishGuard" "$\"$INSTDIR\\PhishGuard.exe$\""
            SectionEnd
            
            ; Uninstaller Section
            Section "Uninstall"
                ; Remove files
                Delete "$INSTDIR\\PhishGuard.exe"
                Delete "$INSTDIR\\LICENSE.txt"
                Delete "$INSTDIR\\README.md"
                Delete "$INSTDIR\\Uninstall.exe"
                
                ; Remove shortcuts
                Delete "$SMPROGRAMS\\PhishGuard\\PhishGuard.lnk"
                Delete "$SMPROGRAMS\\PhishGuard\\Uninstall.lnk"
                Delete "$DESKTOP\\PhishGuard.lnk"
                RMDir "$SMPROGRAMS\\PhishGuard"
                
                ; Remove registry keys
                DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard"
                DeleteRegValue HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Run" "PhishGuard"
                DeleteRegKey HKCU "Software\\PhishGuard"
                
                ; Remove installation directory
                RMDir "$INSTDIR"
            SectionEnd
            """)
        
        # Create a simple LICENSE.txt file
        license_file = os.path.join(project_root, 'LICENSE.txt')
        with open(license_file, 'w') as f:
            f.write("""
            MIT License

            Copyright (c) 2023 PhishGuard

            Permission is hereby granted, free of charge, to any person obtaining a copy
            of this software and associated documentation files (the "Software"), to deal
            in the Software without restriction, including without limitation the rights
            to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
            copies of the Software, and to permit persons to whom the Software is
            furnished to do so, subject to the following conditions:

            The above copyright notice and this permission notice shall be included in all
            copies or substantial portions of the Software.

            THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
            AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
            LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
            OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
            SOFTWARE.
            """)
        
        # Create a simple README.md file
        readme_file = os.path.join(project_root, 'README.md')
        with open(readme_file, 'w') as f:
            f.write("""
            # PhishGuard

            PhishGuard is a Windows application that helps protect you from phishing websites.
            It monitors your web browsers and alerts you when it detects a potential phishing site.

            ## Features

            - Real-time browser monitoring
            - Advanced phishing detection
            - Customizable alert settings
            - System tray integration

            ## Installation

            1. Download the latest installer from the releases page
            2. Run the installer and follow the instructions
            3. PhishGuard will start automatically after installation

            ## Usage

            PhishGuard runs in the background and monitors your web browsers. When it detects a
            potential phishing site, it will display an alert and optionally block access to the site.

            You can access the PhishGuard interface by clicking on the system tray icon.

            ## License

            This project is licensed under the MIT License - see the LICENSE.txt file for details.
            """)
        
        # Convert SVG icon to ICO for Windows
        # In a real implementation, you would use a library like cairosvg or Pillow
        # For this example, we'll just copy the SVG file
        import shutil
        svg_icon = os.path.join(project_root, 'resources', 'icon.svg')
        ico_icon = os.path.join(project_root, 'resources', 'icon.ico')
        shutil.copy(svg_icon, ico_icon)
        
        # Run NSIS to create the installer
        # In a real implementation, you would check if NSIS is installed
        # and run it to create the installer
        logger.info("NSIS command would be run here in a real implementation")
        # subprocess.run(['makensis', nsis_script], cwd=project_root, check=True)
        
        logger.info("Installer created successfully")
        return True
        
    except Exception as e:
        logger.error(f"Error creating installer: {e}")
        return False


if __name__ == "__main__":
    # Set up logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Create the installer
    success = create_installer()
    
    # Exit with appropriate code
    sys.exit(0 if success else 1)